### PR TITLE
fix app out of context when create connection

### PR DESCRIPTION
**Pull request by ntcong**
My proposed fix for #220. Because there's no application context yet, current_app will fail.

Flask's extension guideline tells us to use application context only when we passed it, so we should pass the TESTING condition to _create_connection.

### CODE REVIEW

**Comment by lafrech** [comment]
Thank you @ntcong.

Connection is being reworked by @losintikfos (https://github.com/MongoEngine/flask-mongoengine/issues/98, https://github.com/MongoEngine/flask-mongoengine/issues/71#issuecomment-194261047).

@losintikfos, any advice on this? Any progress on the connection rework?

**Comment by losintikfos** [comment]
@lafrech I have been pretty busy on other projects. I will test the connection re-work to enable us progress on our release plan.

**Comment by lafrech** [comment]
OK, thanks. I didn't mean to rush you.

**Comment by lafrech** [comment]
I forgot about this PR before commenting in https://github.com/MongoEngine/flask-mongoengine/issues/220.

As I said there, if the test about the TESTING config parameter is actually needed, I'd rather pass `app` to `_create_connection` than add a `testing` parameter.

**Comment by lafrech** [comment]
I guess we can close this PR now that https://github.com/MongoEngine/flask-mongoengine/issues/220 is resolved.

**Pull request closed without merging**
