### PR TITLE
Use flask_wtf.FlaskForm instead of deprecated Form

### LINKED ISSUE #265: Warning: flask_wtf.Form has been renamed to "FlaskForm"
flask_mongoengine/wtf/models.py:3: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.

### PR DESCRIPTION
**Pull request by wojcikstefan**
Fixes #265

### CODE REVIEW

**Comment by wojcikstefan** [comment]
@lafrech this should be good to go

**Comment by lafrech** [comment]
The same PR had been submitted a few days ago: https://github.com/MongoEngine/flask-mongoengine/pull/268.

Anyway, do you mind resolving the conflicts?

**Comment by wojcikstefan** [comment]
Ah, didn't notice that other PR. Anyway, this should be good to go and it also doesn't include the unnecessary source code encoding change.

**Comment by lafrech** [comment]
@wojcikstefan Thanks again. Do you mind adding yourself to AUTHORS?

**Comment by wojcikstefan** [comment]
> Do you mind adding yourself to AUTHORS?

#276

**Pull request merged**
