### PR TITLE
Drop old python version, add new python versions to CI/CD

### PR DESCRIPTION
**Pull request by insspb**
- BREAKING CHANGE: Dropped Python v2.6, v2.7, v3.2, v3.3, v3.4 (#355)
- BREAKING CHANGE: Added tests support for python versions: v3.5, v3.6, v3.7, v3.8 (#355)
- BREAKING CHANGE: Minimum Flask version set to v1.1 (#355)
- BREAKING CHANGE: Minimum Flask-WTF version set to v0.14 (#355)
- BREAKING CHANGE: Minimum mongoengine version set to v0.19 (#355)
- BREAKING CHANGE: Minimum mongodb version set to v4.0 (#355)

Travis CI/CD updated to new versions.

### CODE REVIEW

**Comment by lafrech** [comment]
Thanks for the work on this.

I don't use flask-mongoengine anymore and there hasn't been any activity for about two years.

Would you like to join as a maintainer?

**Comment by insspb** [comment]
Codecov cannot be an error here, as I do not change any internal functions, except for one test compatibility change.

**Comment by insspb** [comment]
@lafrech Yes, why not. At least I want to fix most of deprecation warnings, as I use it in production and hate warnings.

**Comment by lafrech** [comment]
@insspb apparently I don't have the credentials to add you to the @MongoEngine/flask-mongoengine team, so I just sent you an invitation to be admin of this repo, since no one in the team seems to object. See #349 (kinda redundant with #71), where you might be able to recruit.

Good luck !

**Pull request closed without merging**
