### PR TITLE
Model form generator now accepts wtf custom 'validators' and 'filters' on model field definition.

### PR DESCRIPTION
**Pull request by losintikfos**
Added a wrapper sub-class WtfBaseField to allow additional WTForm field parameters and settings needed by flask-mongoengine, without necessarily going through to the core mongoengine BaseField.
 - `flask_mongoengine/__init__.py` has patching to redirect wtf mongoengine Fields of base BaseField to use WtfBaseField 
 
 - `wtf/orm.py` now has 'validators' and 'filters' allowed on behalf wtf model field generator.

**Example:**
```
 class Contact(db.Document)
    telephone = db.StringField(
        required=True,
        validators=[
          validators.InputRequired(message=u'Missing telephone.'),
        ],
        max_length=50
    )
```

### CODE REVIEW

**Comment by losintikfos** [comment]
Hi @rozza,

Do you have a timeline for this merge. Do you want me to do anything to get it accepted. I do believe it will resolve some the current tickets and also as an added feature.

**Comment by losintikfos** [comment]
Hi @rozza,

Are there active maintainers for this project? I was also wondering when possibly push request  #147 will be considered?

Thanks

**Comment by rozza** [comment]
@losintikfos I'm really sorry I don't have the bandwidth - but I have invited you to the organisation - so feel free to check the build and merge :)

**Comment by losintikfos** [comment]
@rozza Thanks

**Comment by dizballanze** [comment]
@losintikfos seems what you broke something. 
When I am trying to use version from repo I get following error:
```
Traceback (most recent call last):
  File "/home/vagrant/venv/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/venv/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/vagrant/venv/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/venv/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/vagrant/venv/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/venv/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/venv/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/venv/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/vagrant/venv/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/venv/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/venv/lib/python3.4/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/home/vagrant/venv/lib/python3.4/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/vagrant/venv/lib/python3.4/site-packages/flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "/home/vagrant/proj/fhouse/drafts/views.py", line 40, in post
    form = model_form(Draft)(**data)
  File "/home/vagrant/venv/src/flask-mongoengine/flask_mongoengine/wtf/orm.py", line 275, in model_form
    field_dict = model_fields(model, only, exclude, field_args, converter)
  File "/home/vagrant/venv/src/flask-mongoengine/flask_mongoengine/wtf/orm.py", line 243, in model_fields
    field = converter.convert(model, model_field, field_args.get(name))
  File "/home/vagrant/venv/src/flask-mongoengine/flask_mongoengine/wtf/orm.py", line 50, in convert
    'validators': [] if not field.validators else field.validators,
AttributeError: 'ObjectIdField' object has no attribute 'validators'
```

**Comment by losintikfos** [comment]
@dizballanze thanks for reporting this - I am having a quick look into this.

**Comment by losintikfos** [comment]
@dizballanze update your local version with the fix and try again - thanks.

**Comment by dizballanze** [comment]
@losintikfos problem solved - thanks! :smile_cat:

**Comment by losintikfos** [comment]
Hi @dizballanze, I just pushed a fix to handle both validators and filters. Can you please update your version and confirm it still works fine.

Thanks

**Comment by dizballanze** [comment]
@losintikfos I have checked, it still works.

**Comment by losintikfos** [comment]
@dizballanze Thanks.

**Pull request merged**
