### PR TITLE
Code quality improvements

### PR DESCRIPTION
**Pull request by wojcikstefan**
This is a follow-up after #270. I tightened flake8's code checking, added flake8-import-order and fixed existing imports (see https://www.python.org/dev/peps/pep-0008/#imports for details), and added some minor style tweaks.

@lafrech let me know what you think :)

### CODE REVIEW

**Comment by lafrech** [comment]
Looks good! Great!

Did you intentionally remove host uri parsing in _resolve_settings?

**Comment by wojcikstefan** [comment]
> Did you intentionally remove host uri parsing in _resolve_settings?

Yep, I removed it since it was commented out. If we need to bring it back, it's still in the git history. Appreciate you double-checking it though!

**Comment by wojcikstefan** [comment]
I just did a self-review as a sanity check and everything looks good to me. One other thing I'd like to get rid of completely is the ugly `dict.items() if (sys.version_info >= (3, 0)) else dict.iteritems()` style. It makes the code less readable and the performance boost we'd get in Py2.x from using iteritems is negligible. We're talking about microseconds in a package that by nature interacts with databases (think milliseconds  *at least*). Readability is more important is such cases.

**Comment by lafrech** [comment]
Oh, I didn't see that code was commented out (it wasn't obvious when using colored split diff on GitHub).

TBH, I didn't check every line. I trust you on keeping this low-level and sticking to style changes. Hence my surprise about what appeared to me like a feature removal.

I also hope the tests would have pointed a breaking change.

I'm merging this.

Thanks.

BTW, you're achieving a lot of work on flask-mongoengine, lately. Would you like to join the team?

**Comment by wojcikstefan** [comment]
> I trust you on keeping this low-level and sticking to style changes. 

Thanks. I like sending separate PRs for separate issues so that things are easier to review, easier to revert, and easier to blame :) Hence this PR didn't alter any logic.

> BTW, you're achieving a lot of work on flask-mongoengine, lately. Would you like to join the team?

I'd love to! We just started working on a new service at my company and we decided to use upstream mongoengine/flask-mongoengine (as opposed to our forks), hence I expect to pay a lot of attention to this repo.

**Comment by lafrech** [comment]
@MongoEngine/flask-mongoengine, @MongoEngine/mongoengine, could anybody with admin privileges add @wojcikstefan to the organization and to both teams?

(And perhaps also give me admin privileges on flask-mongoengine repo. Apparently, I can only access MongoEngine settings.)

Thanks.

**Comment by wojcikstefan** [comment]
@MongoEngine/flask-mongoengine, @MongoEngine/mongoengine looking forward to being part of the team and contributing more :)

**Comment by wojcikstefan** [comment]
@lafrech do you have a way to contact the admins? I'd love to join the team sooner rather than later, so that I can spend some spare time triaging issues :)

**Comment by lafrech** [comment]
@wojcikstefan see https://github.com/MongoEngine/mongoengine/issues/1342#issuecomment-256569574.

You can also try to catch up with team members on IRC:

- http://webchat.freenode.net/?channels=flask-mongoengine
- http://webchat.freenode.net/?channels=mongoengine

**Comment by thedrow** [comment]
My apologies for the late response.
@wojcikstefan I just added you to the flask-mongoengine team.
@lafrech I made you the maintainer of the team.
Great job!

**Pull request merged**
